---
- name: Download Hadoop
  get_url: 
    url: "https://archive.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_tmp }}/hadoop-{{ hadoop_version }}.tar.gz"

- name: Unzip Hadoop
  shell: "tar zxf {{ hadoop_tmp }}/hadoop-{{hadoop_version}}.tar.gz -C {{ hadoop_home_path }}"

- name: Remove zip file
  file:
    state: absent
    path: "{{ hadoop_tmp }}/"
  when: del_file_flag