- hosts: master
  gather_facts: true
  become: true
  vars_files:
    - custom_vars/kubernate.yaml
  roles:
    - role: setup-kubernetes/master

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - role: setup-kubernetes/workers
# - hosts: master
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: kubernetes/master, tags: master }
#     - { role: cni, tags: cni }
