- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].host_ip }} {{ hostvars[item].host_name }}"
      when: hostvars[item].host_name is defined and hostvars[item].host_ip != host_ip
      with_items: "{{ groups.all }}"

