- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].host_ip }} {{ hostvars[item].host_name }}"
      when: hostvars[item].host_name is defined
      with_items: "{{ groups.all }}"
    # - name: "dump variables hostvars"
    #   debug: var=local_dns_hosts
